apiVersion: v1
kind: Pod
metadata:
  name: hostpath-test
  annotations:
    description: A pod with a hostPath volume type
spec:
  volumes:
    - name: docker-sock
      hostPath:
        path: /home/vagrant/k8s/pods/gatling/user-files/simulations    # A file or directory location on the node that you want to mount into the Pod
      #  command: [ "git clone https://github.com/TarunKDas2k18/PerfGatl.git" ]

  containers:
    - name: gatlingperftool
      image: tarunkumard/gatling:FirstScript     # Run the ubuntu 16.04
      command: [ "/bin/bash", "-c", "--" ]       # You need to run some task inside a container to keep it running
      args: [ "while true; do sleep 10; done;" ] # Our simple program just sleeps inside an infinite loop
      volumeMounts:
        - mountPath: /opt/gatling/user-files/simulations     # The mount path within the container
          name: docker-sock                   # Name must match the hostPath volume name
      ports:
        - containerPort: 80